name: CI test build

on:
  push:
      branches:
        - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101

    - name: Get current time
      uses: MyJetTools/get-current-time@v2
      id: current-time
      with:
        format: YYYY-MM-DD HH:mm:ss
        utcOffset: "+00:00"
        
    - name: Generate build number
      uses: einaregilsson/build-number@v3
      id: buildnumber
      with:
        token: ${{secrets.github_token}}        

    - name: Build
      run: dotnet build --configuration Release /p:AssemblyVersion=0.0.$BUILD_NUMBER
    - name: Test
      run: dotnet test --no-build --configuration Release
    - name: ls
      run: ls

    - name: Publish Service API 
      run: dotnet publish --no-build ./src/Service.BalanceHistory/Service.BalanceHistory.csproj --configuration Release --output ./publish-api

    - name: Publish Service Worker 
      run: dotnet publish --no-build ./src/Service.BalanceHistory.Worker/Service.BalanceHistory.Worker.csproj --configuration Release --output ./publish-worker

    - name: Check Service dir
      run: ls ./publish-api

    - name: Check Service dir
      run: ls ./publish-worker
      
    - name: Publish image API
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        path: ./publish-api
        registry: docker.pkg.github.com
        repository: ${{ secrets.ORG_NAME }}/service.balancehistory/myjetwallet.service.balancehistory-test
        tags: latest
        build_args: app_version=myjetwallet.service.balancehistory-test:latest,app_compilation_date=${{ steps.current-time.outputs.formattedTime }}

    - name: Publish image Worker
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        path: ./publish-worker
        registry: docker.pkg.github.com
        repository: ${{ secrets.ORG_NAME }}/service.balancehistory/myjetwallet.service.balancehistory.worker-test
        tags: latest
        build_args: app_version=myjetwallet.service.balancehistory.worker-test:latest,app_compilation_date=${{ steps.current-time.outputs.formattedTime }}
